### ISSUE TITLE
Attributing eps consistently

### ISSUE THREAD

**Issue by nikwitt** [SpM-lab/irbasis3#19]
I have noticed an incosistency in the input of eps for the holding class `FiniteTempBasisSet`. Different to `IRbasis` or `FiniteTempBasis`, it does not have `eps=None` as standard input. For ease of use this should probably be consistent.

On the same note, I noticed that eps is added as an attribute in `FiniteTempBasisSet` (line 53), but not in the original  `IRbasis`/`FiniteTempBasis` instances. Would it not be more consistent to add it there instead or even pass it from the SVE decomposition (and then add eps as a property in the holding class)?
It has the advantage that eps could be saved in/reused from metadata of calculation files more easily. Then, eps should be saved after SVD, so that it can be looked up after not setting eps/using `eps=None` as an input.

I would have created a PR to fix the inconsistency in `FiniteTempBasisSet`, but I am not sure about your thoughts on the rest.

**Comment by mwallerb** [comment]
Thanks for bringing this up!

I agree with you!  Feel free to have a go if you like :)

**Comment by nikwitt** [comment]
Summarizing the discussion in #20 (citing Markus):

> I would suggest instead to replace the tuple u, s, v we return as sve_result with a structure SVEResult, which has u, s, v as members but also the kernel, eps, work dtype. This way we can store this with any higher-level object and expose it to the user.
